listen_address: :9395
metric_path: /metrics
log_path: /var/log/nginx/access.log
log_format: '$remote_addr - $remote_user [$time_local] "$method $endpoint $http_version" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
routes:
  - '/endpoint1/*'
